### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by Raspbarrel** [KH2FM-Mods-Num/GoA-ROM-Edition#31]
Ignore my previous post, I clicked on enter by mistake.

Anyway, I'm new to KH2 Randomizer and i am having a problem with GoA Rom.

Everytime I build and run on OpenKH it gives me this error:  
![erroronkh2](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/139450064/3ef94660-bfca-48a6-877e-f454d7457102)

Not sure this is an actual problem with the mod or OpenKH itself, either way, is someone able to give some assistance? I can't find anything about this

**Comment by 1234567890num** [comment]
Maybe try changing the region of your Mods Manager to default and use `Rikysonic-Languagepack-EN` and see if the issue persists.

**Comment by Raspbarrel** [comment]
> Maybe try changing the region of your Mods Manager to default and use `Rikysonic-Languagepack-EN` and see if the issue persists.

Omg thank you this actually worked! Sorry for the late reply, but for anyone else having this issue just do what he said. I had to 'reinstall' OpenKH for it to work, but putting region on default solves it! I'm also going to try it on the PC version soon now that I have it!
