### ISSUE TITLE
Help when I load a world specifically Disney Castle, Simulated Twilight Town, Real Twilight town, The World That Never Was, Pride Lands, Halloween Town. and im on Pcsx2-EX

### ISSUE THREAD

**Issue by kh1isgoodpikachu** [KH2FM-Mods-Num/GoA-ROM-Edition#32]
![disney castle](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/17f3553f-89a7-4221-8e00-0b878ec72d23)
Disney castle^
![simulated twilight town](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/2e1c3476-4281-4f32-82b1-8e0351bd57b0)
Simulated Twilight Town^
![Pride Lands](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/460fff4d-cdc4-48f3-9e83-151a448db8c0)
Pride lands ^
![World that never was](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/c592b592-b550-48a2-b973-34f0b20989b4)
The World that never was^
![holloween town](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/20724c17-574c-4815-b63b-fbc1cfb3ea20)
Halloween Town^
![Real Twilight town](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/assets/140356835/afcd6296-12f5-42bc-b305-84ed642cc7ea)
Real Twilight Town^

Idk why it wont work I'm on randomizer btw here is proof if you want the video [Proof.zip](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/files/12140408/Proof.zip)

And also I was using 1.53.4 it was prob glitchy can someone give me 1.53.3

**Comment by kh1isgoodpikachu** [comment]
[Proof.zip](https://github.com/KH2FM-Mods-Num/GoA-ROM-Edition/files/12140400/Proof.zip)
Here is Proof if you want video

**Comment by kh1isgoodpikachu** [comment]
i waited for 1 hour and no response?

**Comment by kh1isgoodpikachu** [comment]
@1234567890num pls fix these I need help

**Comment by 1234567890num** [comment]
The lua file seems to not be loaded. Make sure to either copy the lua file from the mod into the scripts folder or change PCSX2-EX's settings to to the folder created by the mods manager.

You can join the ()[https://discord.gg/kh2fmrando

**Comment by kh1isgoodpikachu** [comment]
how do I change the settings

**Comment by kh1isgoodpikachu** [comment]
how do I change the settings for the PCSX2-EX use lua files in folders @1234567890num?
