### ISSUE TITLE
Consider moving QoL changes in to GoA script(s)

### ISSUE THREAD

**Issue by paulblessing** [KH2FM-Mods-Num/GoA-ROM-Edition#5]
As an attempt to remove one more piece of setup / one more point of failure / one more thing to troubleshoot, maybe we consider doing this? Even though Val's generator had these QoL changes as optional, there doesn't seem to be a reason on the surface that anyone would want to play rando without them enabled.

The one thing that came up in Discord chat when this was suggested was that the rando converter might need to be updated to stop doing conversion for the QoL settings if this change does get made.

If it's not possible or if it's not the best idea for some reason that hasn't been thought of yet, no worries. Just always trying to simplify initial setup/troubleshooting as much as possible.

**Comment by 1234567890num** [comment]
Done in 1.53.2
